% New Report Class by Manuel Pacheco

\NeedsTeXFormat{LaTeX2e} % Project Started with version date [2016/02/01]
\ProvidesClass{internship}[2017/03/17 USB Internship Report]
\LoadClass[12pt]{report}% Based on the 'report' LaTeX class

\usepackage[utf8]{inputenc} % Character encoding (allows Spanish characters)
\usepackage[spanish]{babel} % Spanish language configuration
\usepackage{anysize} % For page configuration
\usepackage[T1]{fontenc} % For output font proper encoding (correct copy-paste)

% Paragraph configuration
\tolerance=1000
\hbadness=10000
\raggedbottom

% Page Configuration
\setlength{\headheight}{15pt}
\marginsize{3cm}{2cm}{2cm}{2cm}
