% New Report Class by Manuel Pacheco

\NeedsTeXFormat{LaTeX2e} % Project Started with version date [2016/02/01]
\ProvidesClass{report}[2017/03/17 USB Internship Report]

% Based on the 'book' LaTeX class
\LoadClass{book}

\usepackage[letter, center, pdflatex]{crop} % Paper Configuration
\usepackage[utf8]{inputenc} % Character encoding (allows Spanish characters)
\usepackage[spanish]{babel} % Spanish Language Configuration
